services:
  boardgames_redis:
    image: redis:latest
    container_name: boardgames_redis
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "22004:6379"
    networks:
      - boardgames_net

networks:
  boardgames_net:
    external: true