services:
  boardgames_mysql:
    image: mysql:latest
    container_name: boardgames_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: XgZ6KVipdRgqcuhY
    ports:
      - "22003:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - boardgames_net

networks:
  boardgames_net:
    external: true
